upstream ufv_backend {
    server 10.1.1.10:3001;
    server 10.1.1.11:3001;
}

server {
    listen 80;
    server_name _;

    location /static/ {
        alias /var/www/public/;
    }

    location / {
        root /var/www/public;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /profesores/ {
        proxy_pass http://ufv_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
